development: &default
  adapter: mysql2
  host: localhost
  database: elvo_auth_development
  username: root

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

production:
  <<: *default
